version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: cml-postgres
    environment:
      POSTGRES_DB: cml
      POSTGRES_USER: cml
      POSTGRES_PASSWORD: cml
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: cml-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: cml
      RABBITMQ_DEFAULT_PASS: cml

  minio:
    image: minio/minio:RELEASE.2024-04-18T19-09-19Z
    container_name: cml-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data:
