spring:
  config:
    activate:
      on-profile: prod
  main:
    banner-mode: "off"
    lazy-initialization: false  # ❌ БЫЛО TRUE - блокировало RabbitMQ consumers!
  datasource:
    url: jdbc:postgresql://164.90.180.120/eurolinecloud
    username: behruz
    password: 234Bex456
    hikari:
      maximum-pool-size: 100  # Увеличено с 50 до 100 для высокой нагрузки
      minimum-idle: 30  # Увеличено с 20 до 30
      connection-timeout: 10000  # Уменьшено с 15 до 10 сек
      idle-timeout: 240000
      max-lifetime: 540000  # 9 минут (меньше чем PostgreSQL wait_timeout)
      validation-timeout: 5000
      leak-detection-threshold: 60000
      keepalive-time: 300000  # 5 минут keepalive
  servlet:
    multipart:
      max-file-size: ${MULTIPART_MAX_FILE_SIZE:30MB}
      max-request-size: ${MULTIPART_MAX_REQUEST_SIZE:32MB}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 100
          fetch_size: 50
        connection.provider_disables_autocommit: false
        generate_statistics: false
  task:
    execution:
      pool:
        core-size: 16
        max-size: 64
        queue-capacity: 1000
      thread-name-prefix: async-
    scheduling:
      pool:
        size: 8
  mvc:
    log-request-details: false
  cache:
    type: redis
    redis:
      time-to-live: 3600000
  jackson:
    serialization:
      write-dates-as-timestamps: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:cml}
    password: ${RABBIT_PASSWORD:cml}
    connection-timeout: 30000
    requested-heartbeat: 30  # Heartbeat каждые 30 секунд
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2000
          max-attempts: 3
          max-interval: 10000
          multiplier: 2

server:
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
  tomcat:
    threads:
      max: ${SERVER_TOMCAT_MAX_THREADS:400}
      min-spare: ${SERVER_TOMCAT_MIN_SPARE_THREADS:50}
    accept-count: ${SERVER_TOMCAT_ACCEPT_COUNT:500}
    connection-timeout: 15000
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/plain,text/css,text/javascript,application/javascript
    min-response-size: 1024

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type: WARN
    autoparts.kz: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%X{traceId:-}] [%thread] %logger - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized
      probes:
        enabled: true

integration:
  push:
    enabled: false

outbox:
  publisher:
    delay-ms: 15000

cml:
  username: 1c_exchange
  password: 234Euroline456
  allowed-ips: ${CML_ALLOWED_IPS:127.0.0.1}
  queue:
    exchange: ${CML_QUEUE_EXCHANGE:cml.exchange}
    catalog-routing-key: ${CML_CATALOG_ROUTING_KEY:catalog.import}
    offers-routing-key: ${CML_OFFERS_ROUTING_KEY:offers.import}
    orders-export-routing-key: ${CML_ORDERS_EXPORT_ROUTING_KEY:orders.export}
    orders-apply-routing-key: ${CML_ORDERS_APPLY_ROUTING_KEY:orders.apply}
    orders-integration-routing-key: ${CML_ORDERS_INTEGRATION_ROUTING_KEY:orders.integration}
    returns-integration-routing-key: ${CML_RETURNS_INTEGRATION_ROUTING_KEY:returns.integration}
  max-file-size-mb: ${CML_MAX_FILE_SIZE_MB:50}
  max-unzipped-size-mb: ${CML_MAX_UNZIPPED_SIZE_MB:500}
  batch-size: ${CML_BATCH_SIZE:5000}
  orders-export-interval-ms: ${CML_ORDERS_EXPORT_INTERVAL_MS:300000}

app:
  cors:
    allowed-origins: https://admin.euroline.1edu.kz,https://euroline.1edu.kz

# UMAPI.ru Integration
umapi:
  base-url: https://api.umapi.ru
  locale: ru-RU
  api-key: b9a8ccd2-40b1-4e94-9d34-31674c64649f
  timeout:
    connect: 5000
    read: 10000
  retry:
    max-attempts: 3
    backoff-delay: 1000
